using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cinemachine;

public class CameraScript : MonoBehaviour
{
    public CinemachineFreeLook cam;

    [Header("בחמנ ךאלונ")]

    public float defaultFOV = 45.0f;
    [SerializeField] private float runFOV;
    [Space]
    [SerializeField] private float toDefaultSpeed = 0.01f;
    [SerializeField] private float toActionSpeed = 0.01f;

    private void Start()
    {
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }
    private void Update()
    {
        runFOV = defaultFOV + 5f;
        if (PlayerMovement.isRunning)
        {
            cam.m_Lens.FieldOfView = Mathf.Lerp(cam.m_Lens.FieldOfView, runFOV, toActionSpeed);
        }
        else
        {
            cam.m_Lens.FieldOfView = Mathf.Lerp(cam.m_Lens.FieldOfView, defaultFOV, toDefaultSpeed);
        }

    }
}
